# Generated by Django 5.0.1 on 2024-01-27 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('wanted', 'Quero ler'), ('waiting', 'Aguardando'), ('reading', 'Lendo'), ('read', 'Lido')], default='waiting', max_length=20)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='autore.autor')),
            ],
        ),
    ]
